name: "Ruby on Rails CI: Build"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build_app]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
      OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database
        run: bin/rails db:create db:migrate # RAILS_ENV=production

      - name: Precompile assets
        run: bin/rails assets:precompile # RAILS_ENV=production

      - name: Check if Rails app boots
        run: bin/rails runner "puts 'Rails app boots successfully!'"

      # - name: Trigger Deploy Workflow
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     # token: ${{ secrets.GITHUB_TOKEN }}
      #     event-type: deploy_app
