name: "Ruby on Rails CI: RSpec"
on:
  push:
  workflow_dispatch:
jobs:
  rspec-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
      OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bundle exec rspec

      - name: Trigger Rubocop Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: rubocop_app

# name: "Ruby on Rails CI: Rubocop"
# on:
#   workflow_dispatch:
#   repository_dispatch:
#     types: [rubocop_app]  # Triggered by the build workflow

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Force clean repo state
        run: git clean -fdX
      - name: Remove old cache
        run: rm -rf ~/.rubocop_cache
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel --config .rubocop.yml
      - name: Trigger Build Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: build_app
