name: "Ruby on Rails CI: Rubocop"
on: push
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel --config .rubocop.yml
      # - name: Migrate stuff
      #   run: bundle exec rubocop -a --only Migration/DepartmentName
      # - name: Generate binstubs
      #   run: bundle binstubs bundler-audit brakeman rubocop
      # - name: Security audit dependencies
      #   run: bin/bundler-audit --update
      # - name: Security audit application code
      #   run: bin/brakeman -q -w2
